###
# Device Controller
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: device-controller
  name: device-controller
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: application
      component: device-controller
  template:
    metadata:
      labels:
        cluster: application
        component: device-controller
    spec:
      containers:
      - name: device-controller
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/device-controller:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--threshold=30000"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
