kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: aapplication
    component: device-controller
  name: device-controller-authx-config
  namespace: __NPH_NAMESPACE
data:
  # Primitives: ORG, APPS, RESOURCES, PROFILE
  authx-config.json: |
    {"allows_all":false,
     "permissions": {
       "/device_controller.Connection/Ping":{"must":["DEVICE"]},
       "/device_controller.Connection/RegisterLatency":{"must":["DEVICE"]},
       "/device_controller.Connection/SelectCluster":{"must":["DEVICE"]}
     }
    }