###
# Device Controller
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: device-controller
  name: device-controller
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: application
      component: device-controller
  template:
    metadata:
      labels:
        cluster: application
        component: device-controller
    spec:
      containers:
      - name: device-controller
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/device-controller:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--threshold=100"
        - "--clusterAPIHostname=$(CLUSTER_API_HOST)"
        - "--clusterAPIPort=443"
        - "--loginHostname=$(LOGIN_API_HOST)"
        - "--loginPort=443"
        - "--useTLSForLogin=true"
        - "--email=$(EMAIL)"
        - "--password=$(PASSWORD)"
        - "--authConfigPath=/nalej/config/authx-device-controller-authx-config.json"
        - "--authHeader=authorization"
        securityContext:
          runAsUser: 2000
        env:
        - name: CLUSTER_API_HOST
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: cluster_api_hostname
        - name: LOGIN_API_HOST
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: login_api_hostname
        - name: CLUSTER_PUBLIC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: cluster_public_hostname
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: cluster-user-credentials
              key: email
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-user-credentials
              key: password
        ports:
        - name: api-port
          containerPort: 5200
        volumeMounts:
        - name: config
          mountPath: "/nalej/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0644
          name: device-controller-authx-config
      imagePullSecrets:
      - name: nalej-registry
